### ISSUE TITLE
Problem in data/AMR/amr_2.0_utils/text_anonymization_rules.json

### ISSUE THREAD

**Issue by leoliner** [jcyk/AMR-gs#19]
I got an error when runing sh preprocess_raw.sh sentence.txt：

> Recategorizing subgraphs...2021年 08月 06日 星期五 23:57:10 CST
[2021-08-06 23:57:11,707 INFO] Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
Traceback (most recent call last):
  File "/data/leon/miniconda3/envs/amrgs/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/leon/miniconda3/envs/amrgs/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/preprocess/text_anonymizor.py", line 250, in <module>
    amr.abstract_map = text_anonymizor(amr)
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/preprocess/text_anonymizor.py", line 61, in __call__
    amr, text_map, max_length, anonym_type, pos_tag
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/preprocess/text_anonymizor.py", line 83, in _abstract
    collected_entities,
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/preprocess/text_anonymizor.py", line 181, in _replace_span
    if length == 1 and self._leave_as_is(start, amr, text_map, anonym_type):
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/preprocess/text_anonymizor.py", line 143, in _leave_as_is
    if is_anonym_type(index, amr, text_map, ['DATE_ATTRS']) and next_token_is(index, 1, amr, r"^''$"):
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/preprocess/text_anonymizor.py", line 28, in is_anonym_type
    return lemma in text_map and text_map[lemma]['ner'] in types

and the `text_map`  above was got by
 `text_anonymizor = TextAnonymizor.from_json(
        os.path.join(args.util_dir, "text_anonymization_rules.json"))`
so i analysis the json file and i find there are two wrong key in this file:
`"span": "Chinese"` in the anonym_type of `named-entity` 
and
`"span": "2002 08 28"` in the anonym_type of `date-entity`
so i delete them and the error above don't show again.

I guess the key of "span" was mis-written in the `text_anonymization_rules.json`, is that right?

**Comment by leoliner** [comment]
I found an error also originated from this file 
`RAMS_1.0/AMR-gs-master/data/AMR/amr_2.0_utils/text_anonymization_rules.json`
when I run `sh postprocess_2.0.sh`

> multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/leon/miniconda3/envs/amrgs/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/leon/miniconda3/envs/amrgs/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/postprocess/postprocess.py", line 27, in postprocess2
    for amr in expander.expand_file(file_path + '.frame.wiki'):
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/postprocess/expander.py", line 68, in expand_file
    self.expand_graph(amr)
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/postprocess/expander.py", line 94, in expand_graph
    self.expand_ordinal_node(node, saved_dict, amr)
  File "/data/leon/LP4EE/RAMS_1.0/AMR-gs-master/stog/data/dataset_readers/amr_parsing/postprocess/expander.py", line 169, in expand_ordinal_node
    graph.add_node_attribute(node, 'value', int(saved_dict['ops'][0]))
ValueError: invalid literal for int() with base 10: '"-1"'

I guess the reason for this error is that there is a problem with the value of the key "ops" in this json
`"ops": ["\"-1\""]` and `"ops": ["\"-4\""]` 
so I edit this file again by change:
`"ops": ["\"-1\""]` and `"ops": ["\"-4\""]` to`"ops": ["-1"]` and `"ops": ["-4"]` 
and do `sh preprocess_raw.sh` -> `sh work.sh` -> `sh postprocess_2.0.sh` 

at last I got `xx.pred.post` and the information from terminal like this:

> [2021-08-14 22:42:27,415 INFO] Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
ckpt/amr2.0.bert.gr/ckpt.pt_train_out.pred data/AMR/amr_2.0_utils
Something went wrong!!!
[2021-08-14 22:45:46,307 INFO] Restored 44947 name nodes.
[2021-08-14 22:45:46,308 INFO] Expanded 46538 name nodes.
[2021-08-14 22:45:46,308 INFO] Expanded 4619 date nodes.
[2021-08-14 22:45:46,308 INFO] Expanded 1 score nodes.
[2021-08-14 22:45:46,308 INFO] Expanded 1135 ordinal nodes.
[2021-08-14 22:45:46,308 INFO] Expanded 9342 quantities.
[2021-08-14 22:45:46,308 INFO] Expanded 2 urls.
Done.2021年 08月 14日 星期六 22:45:46 CST

it shows that something went wrong by assert `Something went wrong!!!` 
but I don't know where it from, could you help me?  :-)

**Comment by jcyk** [comment]
Hi @leoliner ,

The preprocessing scripts were borrowed from [stog](https://github.com/sheng-z/stog).  To be honest, I do not fully understand the details. Pls see if you can find help there.
